services:
    adstacy.subscriber.image_serializer:
        class: Adstacy\ApiBundle\EventSubscriber\ImageSerializerSubscriber
        arguments: [@service_container]
        tags:
            - { name: jms_serializer.event_subscriber, event: serializer.post_serialize, method: onPostSerialize } 

    adstacy.subscriber.user_has_follow:
        class: Adstacy\ApiBundle\EventSubscriber\UserHasFollowSubscriber
        arguments: [@service_container]
        tags:
            - { name: jms_serializer.event_subscriber, event: serializer.post_serialize, method: onPostSerialize } 
