imports:
    - { resource: config.yml }

parameters:
    facebook_app_id: '138676862997429'
    facebook_app_secret: '09a25b9562d2927df1e49e8d5dfee8b5'
    router.request_context.host: adstacy.dev
    router.request_context.scheme: http
    adstacy.host: http://adstacy.dev

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: false

swiftmailer:
    disable_delivery: true

ornicar_apc:
    host: http://adstacy.dev
    web_dir: %kernel.root_dir%/../web
    mode: curl
