imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    elfinder.loader: Adstacy\AppBundle\Loader\FMElfinderLoader
    thumb_width: 234
    web_dir: %kernel.root_dir%/../web
    elastica_website_types:
        post:
            mappings:
                tags: { boost: 5 }
            persistence:
                driver: orm
                model: Adstacy\AppBundle\Entity\Post
                provider: ~
                finder: ~
                listener: ~

framework:
    #esi:             ~
    translator:
        fallback: %locale%
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        save_path: %kernel.root_dir%/var/sessions
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        thumb_width: %thumb_width%
    form:
        resources:
            - 'AdstacyAppBundle:Form:fields.html.twig'

assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        less:
            node: %node.path%
            node_paths: [%node.modules_path%]
            apply_to: "\.less$"
        uglifyjs2:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifycss
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Adstacy\AppBundle\Entity\User

hwi_oauth:
    firewall_name: main
    resource_owners:
        facebook:
            type: facebook
            client_id: "138676862997429"
            client_secret: "09a25b9562d2927df1e49e8d5dfee8b5"
            scope: "email"
            infos_url:     "https://graph.facebook.com/me?fields=username,name,email,picture.type(square)"
            paths:
                email: email
                profilepicture: picture.data.url
        twitter:
            type: twitter
            client_id: "VNgnUYWcvjnmLiVHzYNEg"
            client_secret: "RF4WbIdC86hRMLQHj8OIRHDx5nApXRKhj5B4Ah5Rg"
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
            twitter: twitterId
    connect:
        account_connector: adstacy.user.provider

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploadstacy

    filesystems:
        image_fs:
            adapter: image_adapter

vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        image:
            uri_prefix: /uploadstacy
            upload_destination: image_fs
            namer: vich_uploader.namer_origname

liip_imagine:
    filter_sets:
        thumbnail:
            quality: 75
            filters:
                relative_resize: { widen: %thumb_width% }

fos_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    serializer: ~
    indexes:
        website:
            client: default
            index_name: website
            finder: ~
            types: %elastica_website_types%

fos_js_routing:
    routes_to_expose: [ /* ]

fm_elfinder:
    locale: %locale%
    editor: tinymce4
    tinymce_popup_path: "asset[bundles/stafalcontinymce/vendor/tiny_mce/tiny_mce_popup.js]"
    showhidden: false # defaults to false
    fullscreen: true # defaults true, applies to simple and ckeditor editors
    connector:
        debug: false # defaults to false
        roots:       # at least one root must be defined
            uploadstacy:
                driver: LocalFileSystem
                path: files
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                upload_deny: ['all']
                upload_max_size: 2M

stfalcon_tinymce:
    include_jquery: false
    language: %locale%
    selector: '.tinymce'
    theme:
        simple:
            plugins:
                - "advlist autolink lists link image charmap anchor"
                - "fullscreen"
                - "save table contextmenu directionality"
                - "paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            file_browser_callback: elFinderBrowser
