imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: oauth.yml }
    - { resource: liip_imagine.yml }
    - { resource: elasticsearch.yml }

parameters:
    elfinder.loader: Adstacy\AppBundle\Loader\FMElfinderLoader
    max_ads_per_page: 10
    max_users_per_page: 10
    max_comments_per_page: 10
    max_list_broadcasts_per_page: 10
    max_tags_per_page: 50
    max_notifications: 50
    max_who_to_follow: 10
    max_sidebar_recommendation: 3
    max_sidebar_trending: 3

    small_thumb_size: 240
    thumb_width: 498
    profile_pic_size: 100
    desc_length: 255

    adstacy.mail.support: support@adstacy.com
    adstacy.mail.admin: admin@adstacy.com
    adstacy.mail.updates: updates@adstacy.com
    adstacy.mail.info: info@adstacy.com

    facebook_app_id: '476946822391252'
    facebook_app_secret: '10af83878f15f4963c5a0a22fdc0e28b'
    twitter_consumer_key: 'VNgnUYWcvjnmLiVHzYNEg'
    twitter_consumer_secret: 'RF4WbIdC86hRMLQHj8OIRHDx5nApXRKhj5B4Ah5Rg'
    twitter_access_token: '99203298-jKDPmWmMtGSAzgEnH754yvc10t8MFAxPiavf7VOYo'
    twitter_access_token_secret: 'fWhvviE1LmeSNOV4Zt6BBQDyCHL0Dwkog1U1ludcNc'

    web_dir: %kernel.root_dir%/../web
    no_profpic_img: /bundles/adstacyapp/img/nophoto.gif

    translator.class: Funddy\Bundle\JsTranslationsBundle\ReadableTranslator\SymfonyReadableTranslator

framework:
    #esi:             ~
    translator:
        fallback: %locale%
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v1
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        save_path: %kernel.root_dir%/sessions
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        thumb_width: %thumb_width%
        small_thumb_size: %small_thumb_size%
        profile_pic_size: %profile_pic_size%
        max_ads_per_page: %max_ads_per_page%
        max_tags_per_page: %max_ads_per_page%
        max_users_per_page: %max_users_per_page%
        max_who_to_follow: %max_who_to_follow%
        desc_length: %desc_length%
        facebook_app_id: %facebook_app_id%
        adstacy_mail_support: %adstacy.mail.support%
        adstacy_mail_admin: %adstacy.mail.admin%
        adstacy_mail_updates: %adstacy.mail.updates%
    form:
        resources:
            - 'AdstacyAppBundle:Form:fields.html.twig'

assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [%node_modules_path%]
            apply_to: "\.less$"
        uglifyjs2:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs
            mangle: true
        uglifycss:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifycss
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

monolog:
    handlers:
        elastica:
            type: stream
            path: %kernel.root_dir%/logs/elastica.log
            channels: elastica
            bubble: false
        doctrine:
            type: stream
            path: %kernel.root_dir%/logs/doctrine.log
            channels: doctrine
            bubble: false
        security:
            type: stream
            path: %kernel.root_dir%/logs/security.log
            channels: security
            bubble: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      %mailer_port%
    encryption: %mailer_encryption%
    username:  %mailer_user%
    password:  %mailer_password%
    auth_mode: %mailer_auth_mode%
    sender_address: %adstacy.mail.support%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Adstacy\AppBundle\Entity\User
    profile:
        form:
            type: adstacy_profile
    registration:
        form:
            type: adstacy_registration
    change_password:
        form:
            type: adstacy_change_password
    resetting:
        form:
            type: adstacy_resetting
    from_email:
        address: %adstacy.mail.support%
        sender_name: Adstacy Support

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: Adstacy Admin
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
    templates:
        edit: AdstacyAppBundle:Admin:edit.html.twig

ornicar_apc:
    host: %adstacy.host%
    web_dir: %kernel.root_dir%/../web
    mode: curl

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%
            logging: %kernel.debug%

funddy_js_translations:
    languages: [id, en]
    domains: [messages, validators]

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        amazon_s3_image_adapter:
            aws_s3:
                service_id: amazon.s3
                bucket_name: adstacy
                options:
                    directory: uploads
        local_image_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads
