imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    elfinder.loader: Adstacy\AppBundle\Loader\FMElfinderLoader
    max_ads_per_page: 30
    max_users_per_page: 15
    max_notifications: 50
    thumb_width: 234
    mini_thumb_size: 100
    profile_pic_size: 100
    desc_length: 255

    adstacy.mail.support: support@adstacy.com
    adstacy.mail.admin: admin@adstacy.com
    adstacy.mail.updates: updates@adstacy.com

    facebook_app_id: '476946822391252'
    facebook_app_secret: '10af83878f15f4963c5a0a22fdc0e28b'
    twitter_client_id: 'VNgnUYWcvjnmLiVHzYNEg'
    twitter_client_secret: 'RF4WbIdC86hRMLQHj8OIRHDx5nApXRKhj5B4Ah5Rg'

    web_dir: %kernel.root_dir%/../web
    no_profpic_img: /bundles/adstacyapp/img/nophoto.gif
    elastica_website_types:
        ad:
            mappings:
                tags: { boost: 5 }
                created: { type: date }
            persistence:
                driver: orm
                model: Adstacy\AppBundle\Entity\Ad
                provider: ~
                finder: ~
                listener: ~
                elastica_to_model_transformer:
                    ignore_missing: true
        user:
            mappings:
                username: { boost: 5 }
                realname: { boost: 4 }
            persistence:
                driver: orm
                model: Adstacy\AppBundle\Entity\User
                provider: ~
                finder: ~
                listener: ~
                elastica_to_model_transformer:
                    ignore_missing: true

framework:
    #esi:             ~
    translator:
        fallback: %locale%
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v11
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        save_path: %kernel.root_dir%/sessions
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        thumb_width: %thumb_width%
        mini_thumb_size: %mini_thumb_size%
        profile_pic_size: %profile_pic_size%
        max_ads_per_page: %max_ads_per_page%
        max_users_per_page: %max_users_per_page%
        desc_length: %desc_length%
        facebook_app_id: %facebook_app_id%
        adstacy_mail_support: %adstacy.mail.support%
        adstacy_mail_admin: %adstacy.mail.admin%
        adstacy_mail_updates: %adstacy.mail.updates%
    form:
        resources:
            - 'AdstacyAppBundle:Form:fields.html.twig'

assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [%node_modules_path%]
            apply_to: "\.less$"
        uglifyjs2:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifycss
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

monolog:
    handlers:
        elastica:
            type: stream
            path: %kernel.root_dir%/logs/elastica.log
            channels: elastica
            bubble: false
        doctrine:
            type: stream
            path: %kernel.root_dir%/logs/doctrine.log
            channels: doctrine
            bubble: false
        security:
            type: stream
            path: %kernel.root_dir%/logs/security.log
            channels: security
            bubble: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      %mailer_port%
    encryption: %mailer_encryption%
    username:  %mailer_user%
    password:  %mailer_password%
    auth_mode: %mailer_auth_mode%
    sender_address: %adstacy.mail.support%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Adstacy\AppBundle\Entity\User
    profile:
        form:
            type: adstacy_profile
    registration:
        form:
            type: adstacy_registration
    change_password:
        form:
            type: adstacy_change_password
    resetting:
        form:
            type: adstacy_resetting
    from_email:
        address: %adstacy.mail.support%
        sender_name: Adstacy Support

hwi_oauth:
    firewall_name: main
    resource_owners:
        facebook:
            type: facebook
            client_id: %facebook_app_id%
            client_secret: %facebook_app_secret%
            scope: "email"
            infos_url:     "https://graph.facebook.com/me?fields=username,name,email,picture.type(square)"
            paths:
                email: email
                profilepicture: picture.data.url
        twitter:
            type: twitter
            client_id: %twitter_client_id%
            client_secret: %twitter_client_secret%
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
            twitter: twitterId
    connect:
        account_connector: adstacy.user.provider
    http_client:
        timeout: 15
        verify_peer: false

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads

    filesystems:
        image_fs:
            adapter: image_adapter

vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        ad_image:
            uri_prefix: /uploads
            upload_destination: image_fs
            namer: vich_uploader.namer_uniqid
        user_image:
            uri_prefix: /uploads
            upload_destination: image_fs
            namer: vich_uploader.namer_uniqid

liip_imagine:
    filter_sets:
        thumbnail:
            quality: 90
            filters:
                relative_resize: { widen: 480 }
        mini_thumb:
            quality: 50
            filters:
                thumbnail: { size: [%mini_thumb_size%, %mini_thumb_size%], mode: outbound }
        profile_pic:
            quality: 75
            filters:
                thumbnail: { size: [%profile_pic_size%, %profile_pic_size%], mode: outbound }

fos_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    serializer: ~
    indexes:
        website:
            client: default
            index_name: website
            finder: ~
            types: %elastica_website_types%

fm_elfinder:
    locale: %locale%
    editor: tinymce4
    tinymce_popup_path: "asset[bundles/stafalcontinymce/vendor/tiny_mce/tiny_mce_popup.js]"
    showhidden: false # defaults to false
    fullscreen: true # defaults true, applies to simple and ckeditor editors
    connector:
        debug: false # defaults to false
        roots:       # at least one root must be defined
            uploads:
                driver: LocalFileSystem
                path: files
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                upload_deny: ['all']
                upload_max_size: 2M

stfalcon_tinymce:
    include_jquery: false
    language: %locale%
    selector: '.tinymce'
    theme:
        simple:
            plugins:
                - "advlist autolink lists link image charmap anchor"
                - "fullscreen"
                - "save table contextmenu directionality"
                - "paste textcolor"
            toolbar1: "image | bullist numlist outdent indent | link table | fullscreen"
            toolbar2: "insertfile undo redo | styleselect | bold italic forecolor backcolor | alignleft aligncenter alignright alignjustify"
            menubar: false
            file_browser_callback: elFinderBrowser
            height: "300px"

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: Adstacy Admin
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
    templates:
        edit: AdstacyAppBundle:Admin:edit.html.twig

ornicar_apc:
    host: http://www.adstacy.com
    web_dir: %kernel.root_dir%/../web
    mode: curl

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%
            logging: %kernel.debug%
