imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        less:
            node: %node.path%
            node_paths: [%node.modules_path%]
            apply_to: "\.less$"
        uglifyjs2:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifycss

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Ads\AppBundle\Entity\User

hwi_oauth:
    firewall_name: main
    resource_owners:
        facebook:
            type: facebook
            client_id: "138676862997429"
            client_secret: "09a25b9562d2927df1e49e8d5dfee8b5"
            scope: "email"
            infos_url:     "https://graph.facebook.com/me?fields=username,name,email,picture.type(square)"
            paths:
                email: email
                profilepicture: picture.data.url
        twitter:
            type: twitter
            client_id: "VNgnUYWcvjnmLiVHzYNEg"
            client_secret: "RF4WbIdC86hRMLQHj8OIRHDx5nApXRKhj5B4Ah5Rg"
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
            twitter: twitterId

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads

    filesystems:
        image_fs:
            adapter: image_adapter

vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        image:
            uri_prefix: /uploads
            upload_destination: image_fs
            namer: vich_uploader.namer_origname

liip_imagine:
    filter_sets:
        thumbnail:
            quality: 75
            filters:
                relative_resize: { widen: 236 }
