parameters:
    elastica_website_types:
        ad:
            mappings:
                tags: { boost: 1.5, index: not_analyzed, analyzer: tags_analyzer }
                created: { type: date, index: not_analyzed }
                active: ~
            persistence:
                driver: orm
                model: Adstacy\AppBundle\Entity\Ad
                provider: ~
                finder: ~
                listener: ~
                elastica_to_model_transformer:
                    ignore_missing: true
        user:
            mappings:
                username: { boost: 5 }
                realname: { boost: 4 }
                suggestions: { type: completion, preserve_separators: true }
            persistence:
                driver: orm
                model: Adstacy\AppBundle\Entity\User
                provider: ~
                finder: ~
                listener: ~
                elastica_to_model_transformer:
                    ignore_missing: true

fos_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    serializer: ~
    indexes:
        website:
            settings:
                index:
                    analysis:
                        analyzer:
                            tags_analyzer:
                                type: custom
                                tokenizer: keyword
                                filter: [lowercase, asciifolding]
            client: default
            index_name: website
            finder: ~
            types: %elastica_website_types%
