liip_imagine:
    filter_sets:
        thumbnail:
            quality: 90
            filters:
                relative_resize: { widen: %thumb_width% }
        mini_thumb:
            quality: 50
            filters:
                thumbnail: { size: [%mini_thumb_size%, %mini_thumb_size%], mode: outbound }
        profile_pic:
            quality: 75
            filters:
                thumbnail: { size: [%profile_pic_size%, %profile_pic_size%], mode: outbound }
