liip_imagine:
    cache: amazon_s3
    cache_clearer: false
    data_loader: image_fs
    filter_sets:
        small_thumb:
            quality: 100
            filters:
                relative_resize: { widen: %small_thumb_size% }
        profile_pic:
            quality: 75
            filters:
                thumbnail: { size: [%profile_pic_size%, %profile_pic_size%], mode: outbound }
