liip_imagine:
    cache: amazon_s3
    cache_clearer: false
    data_loader: image_fs
    filter_sets:
        thumbnail:
            quality: 90
            filters:
                relative_resize: { widen: %thumb_width% }
        small_thumb:
            quality: 90
            filters:
                thumbnail: { size: [%small_thumb_size%, %small_thumb_size%], mode: inset }
        profile_pic:
            quality: 75
            filters:
                thumbnail: { size: [%profile_pic_size%, %profile_pic_size%], mode: outbound }
