_imagine:
    resource: .
    type:     imagine

adstacy_app:
    resource: "@AdstacyAppBundle/Resources/config/routing.yml"
    prefix:   /

adstacy_notification:
    resource: "@AdstacyNotificationBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /auth/

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /auth/

hwi_oauth_connect_user:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

facebook_login:
    pattern: /login/facebook

twitter_login:
    pattern: /login/twitter

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_profile_edit: # override
    pattern: /settings
    defaults:
        _controller: FOSUserBundle:Profile:edit

fos_user_profile_show: ## hack
    pattern: /settings
    defaults:
        _controller: FOSUserBundle:Profile:show

fos_user_change_password:
    pattern: /settings/change-password
    defaults:
        _controller: FOSUserBundle:ChangePassword:changePassword
    requirements:
        _method: GET|POST

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_registration_confirmed: # hack
    path: /settings
    defaults:
        _controller: FOSUserBundle:Profile:show

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /_admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /_admin

AdstacyAppBundle_user:
    resource: "@AdstacyAppBundle/Resources/config/routing/users.yml"
