security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: adstacy.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            oauth:
                resource_owners:
                    facebook: "/login/facebook"
                    twitter: "/login/twitter"
                login_path: /login
                failure_path: /login
                oauth_user_provider:
                    service: adstacy.user.provider
            form_login:
                provider: fos_userbundle
                csrf_provider:  form.csrf_provider
            logout: true
            anonymous: true
            switch_user: { role: ROLE_SUPER_ADMIN, parameter: _impersonate }
            remember_me:
                always_remember_me: true
                key: SupperrrSec3tttttK3YYAYY
                lifetime: 31536000
                path: /
                domain: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }
