adstacy_notification_show:
    path: /notifications
    defaults:
        _controller: AdstacyNotificationBundle:Notification:showNotifications

adstacy_notification_readall:
    path: /notifications/read-all
    defaults:
        _controller: AdstacyNotificationBundle:Notification:readAll

