adstacy_notification_show:
    pattern: /notifications
    defaults:
        _controller: AdstacyNotificationBundle:Notification:showNotifications

adstacy_notification_readall:
    pattern: /notifications/read-all
    defaults:
        _controller: AdstacyNotificationBundle:Notification:readAll

