services:
    adstacy.notification.notification_saver.comment:
        class: Adstacy\NotificationBundle\NotificationSaver\CommentNotificationSaver
        arguments: [@doctrine.orm.entity_manager]

    adstacy.notification.notification_saver.mention:
        class: Adstacy\NotificationBundle\NotificationSaver\MentionNotificationSaver
        arguments: [@doctrine.orm.entity_manager]

    adstacy.notification.notification_saver.follow:
        class: Adstacy\NotificationBundle\NotificationSaver\FollowNotificationSaver
        arguments: [@doctrine.orm.entity_manager]

    adstacy.notification.notification_saver.promote:
        class: Adstacy\NotificationBundle\NotificationSaver\PromoteNotificationSaver
        arguments: [@doctrine.orm.entity_manager]

    adstacy.notification.notification_saver.block_ad:
        class: Adstacy\NotificationBundle\NotificationSaver\BlockAdNotificationSaver
        arguments: [@doctrine.orm.entity_manager]

    adstacy.notification.notification_saver.unblock_ad:
        class: Adstacy\NotificationBundle\NotificationSaver\UnblockAdNotificationSaver
        arguments: [@doctrine.orm.entity_manager]

    adstacy.notification.notification_saver.facebook_friend_join:
        class: Adstacy\NotificationBundle\NotificationSaver\FacebookFriendJoinNotificationSaver
        arguments: [@doctrine.orm.entity_manager]

    adstacy.notification.notification_saver.twitter_friend_join:
        class: Adstacy\NotificationBundle\NotificationSaver\TwitterFriendJoinNotificationSaver
        arguments: [@doctrine.orm.entity_manager]


    adstacy.notification.notification_formatter.comment:
        class: Adstacy\NotificationBundle\NotificationFormatter\CommentNotificationFormatter
        arguments: [@router, @translator, @adstacy.helper.formatter, @adstacy.helper.user]

    adstacy.notification.notification_formatter.mention:
        class: Adstacy\NotificationBundle\NotificationFormatter\MentionNotificationFormatter
        arguments: [@router, @translator, @adstacy.helper.formatter, @adstacy.helper.user]

    adstacy.notification.notification_formatter.follow:
        class: Adstacy\NotificationBundle\NotificationFormatter\FollowNotificationFormatter
        arguments: [@router, @translator, @adstacy.helper.formatter, @adstacy.helper.user]

    adstacy.notification.notification_formatter.promote:
        class: Adstacy\NotificationBundle\NotificationFormatter\PromoteNotificationFormatter
        arguments: [@router, @translator, @adstacy.helper.formatter, @adstacy.helper.user]

    adstacy.notification.notification_formatter.block_ad:
        class: Adstacy\NotificationBundle\NotificationFormatter\BlockAdNotificationFormatter
        arguments: [@router, @translator, @adstacy.helper.formatter, @adstacy.helper.user]

    adstacy.notification.notification_formatter.unblock_ad:
        class: Adstacy\NotificationBundle\NotificationFormatter\UnblockAdNotificationFormatter
        arguments: [@router, @translator, @adstacy.helper.formatter, @adstacy.helper.user]

    adstacy.notification.notification_formatter.facebook_friend_join:
        class: Adstacy\NotificationBundle\NotificationFormatter\FacebookFriendJoinNotificationFormatter
        arguments: [@router, @translator, @adstacy.helper.formatter, @adstacy.helper.user]

    adstacy.notification.notification_formatter.twitter_friend_join:
        class: Adstacy\NotificationBundle\NotificationFormatter\TwitterFriendJoinNotificationFormatter
        arguments: [@router, @translator, @adstacy.helper.formatter, @adstacy.helper.user]

    adstacy.notification.manager:
        class: Adstacy\NotificationBundle\NotificationManager
        arguments:
            -
                - @adstacy.notification.notification_saver.comment
                - @adstacy.notification.notification_saver.mention
                - @adstacy.notification.notification_saver.follow
                - @adstacy.notification.notification_saver.promote
                - @adstacy.notification.notification_saver.block_ad
                - @adstacy.notification.notification_saver.unblock_ad
                - @adstacy.notification.notification_saver.facebook_friend_join
                - @adstacy.notification.notification_saver.twitter_friend_join
            -
                - @adstacy.notification.notification_formatter.comment
                - @adstacy.notification.notification_formatter.mention
                - @adstacy.notification.notification_formatter.follow
                - @adstacy.notification.notification_formatter.promote
                - @adstacy.notification.notification_formatter.block_ad
                - @adstacy.notification.notification_formatter.unblock_ad
                - @adstacy.notification.notification_formatter.facebook_friend_join
                - @adstacy.notification.notification_formatter.twitter_friend_join

    adstacy.twig.notification_extension:
        class: Adstacy\NotificationBundle\Twig\NotificationExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    adstacy.notification.email_manager:
        class: Adstacy\NotificationBundle\EmailManager
        arguments:
            - @service_container
            - @adstacy.notification.manager
