<?php

namespace Adstacy\NotificationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Adstacy\AppBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function findNotificationsForUserQuery(User $user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT n,
            partial u.{id,username,imagename,realName},
            partial a.{id,imagename,description,tags,thumbHeight,imageHeight,imageWidth,promoteesCount,created}
            FROM AdstacyNotificationBundle:Notification n
            JOIN n.to u
            JOIN n.ad a
            JOIN n.comment c
            WHERE u.id = :id AND n.read = FALSE
            ORDER BY n.created DESC
        ');

        return $query->setParameter('id', $user->getId());
    }
}
