homepage:
    pattern:  /
    defaults:
        _controller: AdsAppBundle:App:index

ads_app_search:
    pattern: /search
    defaults:
        _controller: AdsAppBundle:App:search

ads_app_post_add:
    pattern: /add
    defaults:
        _controller: AdsAppBundle:Post:add

ads_app_wall_add:
    pattern: /walls/add
    defaults:
        _controller: AdsAppBundle:Wall:add
