ads_app_homepage:
    pattern:  /
    defaults:
        _controller: AdsAppBundle:App:index

ads_app_search:
    pattern: /search
    defaults:
        _controller: AdsAppBundle:App:search

ads_app_add:
    pattern: /add
    defaults:
        _controller: AdsAppBundle:Post:add
