services:
    facebook:
        class: Facebook
        arguments:
            -
                appId: %facebook_app_id%
                secret: %facebook_app_secret%

    twitter:
        class: TwitterAPIExchange
        arguments:
            - 
                oauth_access_token: %twitter_access_token%
                oauth_access_token_secret: %twitter_access_token_secret%
                consumer_key: %twitter_client_id%
                consumer_secret: %twitter_client_secret%

    adstacy.oauth.facebook_api:
        class: Adstacy\OAuthBundle\API\FacebookAPI
        arguments: [@facebook]

    adstacy.oauth.twitter_api:
        class: Adstacy\OAuthBundle\API\TwitterAPI
        arguments: [@twitter]
