adstacy_api_user_show:
    path: /{username}
    defaults:
        _controller: AdstacyApiBundle:User:show
    options:
        expose: true

adstacy_api_user_ads:
    path: /{username}/ads
    defaults:
        _controller: AdstacyApiBundle:User:listAds
    options:
        expose: true

adstacy_api_user_followers:
    path: /{username}/followers
    defaults:
        _controller: AdstacyApiBundle:User:listFollowers
    options:
        expose: true

adstacy_api_user_followings:
    path: /{username}/followings
    defaults:
        _controller: AdstacyApiBundle:User:listFollowings
    options:
        expose: true

adstacy_api_user_promotes:
    path: /{username}/promotes
    defaults:
        _controller: AdstacyApiBundle:User:listPromotes
    options:
        expose: true
