services:
    adstacy.type.profile:
        class: Adstacy\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: adstacy_profile }

    adstacy.type.registration:
        class: Adstacy\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: adstacy_registration }

    adstacy.type.change_password:
        class: Adstacy\UserBundle\Form\Type\ChangePasswordFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: adstacy_change_password }

    adstacy.type.resetting:
        class: Adstacy\UserBundle\Form\Type\ResettingFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: adstacy_resetting }

    adstacy.listener.registration_completed:
        class: Adstacy\UserBundle\EventListener\RegistrationCompletedListener
        arguments: [@adstacy.manager.user]
        tags:
            - { name: kernel.event_subscriber }

    adstacy.listener.profile_edit_completed:
        class: Adstacy\UserBundle\EventListener\ProfileEditCompletedListener
        arguments: [@adstacy.manager.user]
        tags:
            - { name: kernel.event_subscriber }
