<?php

namespace Adstacy\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Adstacy\AppBundle\Entity\Ad;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * Find $limit comments by $ad which is older than $until
     *
     * @param Ad $ad
     * @param integer|null $until
     * @param integer $limit
     *
     * @return array
     */
    public function findByAd(Ad $ad, $until = null, $limit = 10)
    {
        if ($until == null) {
            $until = 2000000000;
        }
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT c,
            partial u.{id,username,imagename,realName}
            FROM AdstacyAppBundle:Comment c
            JOIN c.ad a
            JOIN c.user u
            WHERE c.id < :until AND a.id = :id
            ORDER BY c.id DESC
        ');

        return array_reverse($query->setParameter('until', $until)->setParameter('id', $ad->getId())->setMaxResults($limit)->getResult());
    }
}
