<?php

namespace Adstacy\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Adstacy\AppBundle\Entity\Ad;
use Adstacy\AppBundle\Entity\User;

/**
 * PromoteAdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoteAdRepository extends EntityRepository
{
    public function findByAdAndUser(Ad $ad, User $user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT pa
            FROM AdstacyAppBundle:PromoteAd pa
            JOIN pa.ad a
            JOIN pa.user u
            WHERE a.id = :adId AND u.id = :userId
        ');

        return $query
            ->setParameter('adId', $ad->getId())
            ->setParameter('userId', $user->getId())
            ->getSingleResult();
    }
}
