<?php

namespace Adstacy\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TempAdImageRepository 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempAdImageRepository extends EntityRepository
{
}
