<?php

namespace Adstacy\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Adstacy\AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * Find $user followers
     *
     * @param User $user
     *
     * @return array
     */
    public function findFollowersByUser(User $user)
    {
        $em = $this->getEntitymanager();
        $query = $em->createQuery('
            SELECT u
            FROM AdstacyAppBundle:User u
            JOIN u.followings f
            WHERE f.id = :id
        ');

        return $query->setParameter('id', $user->getId())->getResult();
    }

    /**
     * Find $user followings
     *
     * @param User $user
     *
     * @return array
     */
    public function findFollowingsByUser(User $user)
    {
        $em = $this->getEntitymanager();
        $query = $em->createQuery('
            SELECT u.id
            FROM AdstacyAppBundle:User u
            JOIN u.followers f
            WHERE f.id = :id
        ');

        return $query->setParameter('id', $user->getId())->getResult();
    }
    /**
     * Count $user followers
     *
     * @param User $user
     *
     * @return integer
     */
    public function countFollowersByUser(User $user)
    {
        $em = $this->getEntitymanager();
        $query = $em->createQuery('
            SELECT COUNT(u.id)
            FROM AdstacyAppBundle:User u
            JOIN u.followings f
            WHERE f.id = :id
        ');

        return $query->setParameter('id', $user->getId())->getSingleScalarResult();
    }

    /**
     * Count $user followings
     *
     * @param User $user
     *
     * @return integer
     */
    public function countFollowingsByUser(User $user)
    {
        $em = $this->getEntitymanager();
        $query = $em->createQuery('
            SELECT COUNT(u.id)
            FROM AdstacyAppBundle:User u
            JOIN u.followers f
            WHERE f.id = :id
        ');

        return $query->setParameter('id', $user->getId())->getSingleScalarResult();
    }
}
