<?php

namespace Adstacy\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDetailRepository extends EntityRepository
{
}
