<?php

namespace Adstacy\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Adstacy\AppBundle\Entity\User;

/**
 * WallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallRepository extends EntityRepository
{

    /**
     * Find walls by user with its corresponding ads count
     *
     * @param User $user
     *
     * @return array array(0 => Wall, 'adsCount' => integer)
     */
    public function findByUser(User $user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT w, a
            FROM AdstacyAppBundle:Wall w
            JOIN w.user u
            JOIN w.ads a
            WHERE u.id = :id
        ');

        return $query->setParameter('id', $user->getId())->getResult();
    }

    /**
     * Count walls by $user
     *
     * @param User $user
     *
     * @return integer
     */
    public function countByUser(User $user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT COUNT(w.id)
            FROM AdstacyAppBundle:Wall w
            JOIN w.user u
            WHERE u.id = :id
        ');

        return $query->setParameter('id', $user->getId())->getSingleScalarResult();
    }

    /**
     * Return number of walls by $wallUser followed by $user
     *
     * @param User $wallUser
     * @param User $user
     *
     * @return integer
     */
    public function countFollowedByUser(User $wallUser, User $user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT COUNT(w.id)
            FROM AdstacyAppBundle:Wall w
            JOIN w.user u
            JOIN w.followers f
            WHERE u.id = :wall_user_id AND f.id = :user_id
        ');

        return $query->setParameter('wall_user_id', $wallUser->getId())
            ->setParameter('user_id', $user->getId())
            ->getSingleScalarResult()
        ;
    }
}
