adstacy_app_ad_create:
    pattern: /ads/create
    defaults:
        _controller: AdstacyAppBundle:Ad:add

adstacy_app_ad_show:
    pattern: /ads/{id}
    defaults:
        _controller: AdstacyAppBundle:Ad:show
    requirements:
        id: \d+

adstacy_app_ad_promote:
    pattern: /ads/{id}/promote
    defaults:
        _controller: AdstacyAppBundle:Ad:promote
    requirements:
        id: \d+

adstacy_app_ad_unpromote:
    pattern: /ads/{id}/unpromote
    defaults:
        _controller: AdstacyAppBundle:Ad:unpromote
    requirements:
        id: \d+
