adstacy_app_ad_create:
    pattern: /ads/create
    defaults:
        _controller: AdstacyAppBundle:Ad:create

adstacy_app_ad_show:
    pattern: /ads/{id}
    defaults:
        _controller: AdstacyAppBundle:Ad:show
    requirements:
        id: \d+

adstacy_app_ad_promotes:
    pattern: /ads/{id}/promotes
    defaults:
        _controller: AdstacyAppBundle:Ad:showPromotes
    requirements:
        id: \d+

adstacy_app_ad_promote:
    pattern: /ads/{id}/promote
    defaults:
        _controller: AdstacyAppBundle:Ad:promote
    requirements:
        id: \d+

adstacy_app_ad_unpromote:
    pattern: /ads/{id}/unpromote
    defaults:
        _controller: AdstacyAppBundle:Ad:unpromote
    requirements:
        id: \d+

adstacy_app_ad_comment:
    pattern: /ads/{id}/comment
    defaults:
        _controller: AdstacyAppBundle:Ad:comment
    requirements:
        id: \d+
    methods: [POST]

adstacy_app_ad_comment_delete:
    pattern: /comments/{id}/delete
    defaults:
        _controller: AdstacyAppBundle:Ad:deleteComment
    requirements:
        id: \d+
    methods: [POST]

adstacy_app_ad_edit:
    pattern: /ads/{id}/edit
    defaults:
        _controller: AdstacyAppBundle:Ad:edit
    requirements:
        id: \d+

adstacy_app_ad_delete:
    pattern: /ads/{id}/delete
    defaults:
        _controller: AdstacyAppBundle:Ad:delete
    requirements:
        id: \d+

adstacy_app_ad_report:
    pattern: /ads/{id}/report
    defaults:
        _controller: AdstacyAppBundle:Ad:report
    requirements:
        id: \d+
