adstacy_app_api_users:
    path: /users.json
    defaults:
        _controller: AdstacyAppBundle:Api:users
    options:
      expose: true

adstacy_app_api_network:
    path: /network.json
    defaults:
        _controller: AdstacyAppBundle:Api:network
    options:
        expose: true

adstacy_app_api_tags:
    path: /tags.json
    defaults:
        _controller: AdstacyAppBundle:Api:tags
    options:
      expose: true
