adstacy_app_api_users:
    path: /users.json
    defaults:
        _controller: AdstacyAppBundle:Api:users
    options:
      expose: true

adstacy_app_api_network:
    path: /network.json
    defaults:
        _controller: AdstacyAppBundle:Api:network
    options:
        expose: true

adstacy_app_api_tags:
    path: /tags.json
    defaults:
        _controller: AdstacyAppBundle:Api:tags
    options:
      expose: true

adstacy_app_api_user_show:
    path: /users/{username}
    defaults:
        _controller: AdstacyAppBundle:Api:showUser
    options:
        expose: true

adstacy_app_api_user_ads:
    path: /users/{username}/ads
    defaults:
        _controller: AdstacyAppBundle:Api:listAds
    options:
        expose: true

adstacy_app_api_user_followers:
    path: /users/{username}/followers
    defaults:
        _controller: AdstacyAppBundle:Api:listFollowers
    options:
        expose: true

adstacy_app_api_user_followings:
    path: /users/{username}/followings
    defaults:
        _controller: AdstacyAppBundle:Api:listFollowings
    options:
        expose: true

adstacy_app_api_user_promotes:
    path: /users/{username}/promotes
    defaults:
        _controller: AdstacyAppBundle:Api:listPromotes
    options:
        expose: true
