adstacy_app_search:
    pattern: /search
    defaults:
        _controller: AdstacyAppBundle:Search:search

adstacy_app_search_ads:
    pattern: /search/ads
    defaults:
        _controller: AdstacyAppBundle:Search:searchAds

adstacy_app_search_users:
    pattern: /search/users
    defaults:
        _controller: AdstacyAppBundle:Search:searchUsers
