adstacy_app_search:
    path: /search
    defaults:
        _controller: AdstacyAppBundle:Search:search
    options:
        expose: true

adstacy_app_search_users:
    path: /search/users
    defaults:
        _controller: AdstacyAppBundle:Search:searchUsers
    options:
        expose: true
