adstacy_app_user_profile:
    pattern: /{username}
    defaults:
        _controller: AdstacyAppBundle:User:show

adstacy_app_user_activity:
    pattern: /{username}/activity
    defaults:
        _controller: AdstacyAppBundle:User:showActivity

adstacy_app_user_ads:
    pattern: /{username}/ads
    defaults:
        _controller: AdstacyAppBundle:User:showAds

adstacy_app_user_followers:
    pattern: /{username}/followers
    defaults:
        _controller: AdstacyAppBundle:User:showFollowers

adstacy_app_user_followings:
    pattern: /{username}/followings
    defaults:
        _controller: AdstacyAppBundle:User:showFollowings

adstacy_app_user_follow:
    pattern: /{username}/follow
    defaults:
        _controller: AdstacyAppBundle:User:follow

adstacy_app_user_unfollow:
    pattern: /{username}/unfollow
    defaults:
        _controller: AdstacyAppBundle:User:unfollow
