adstacy_app_user_profile:
    path: /{username}
    defaults:
        _controller: AdstacyAppBundle:User:show
    options:
        expose: true

adstacy_app_user_promotes:
    path: /{username}/broadcasts
    defaults:
        _controller: AdstacyAppBundle:User:showPromotes

adstacy_app_user_ads:
    path: /{username}/ads
    defaults:
        _controller: AdstacyAppBundle:User:showAds

adstacy_app_user_followers:
    path: /{username}/followers
    defaults:
        _controller: AdstacyAppBundle:User:showFollowers

adstacy_app_user_followings:
    path: /{username}/followings
    defaults:
        _controller: AdstacyAppBundle:User:showFollowings

adstacy_app_user_follow:
    path: /{username}/follow
    defaults:
        _controller: AdstacyAppBundle:User:follow
    options:
        expose: true

adstacy_app_user_unfollow:
    path: /{username}/unfollow
    defaults:
        _controller: AdstacyAppBundle:User:unfollow
    options:
        expose: true
