adstacy_app_wall_show:
    pattern: /walls/{id}
    defaults:
        _controller: AdstacyAppBundle:Wall:show
    requirements:
        id: \d+

adstacy_app_wall_follow:
    pattern: /walls/{id}/follow
    defaults:
        _controller: AdstacyAppBundle:Wall:follow
    requirements:
        id: \d+

adstacy_app_wall_unfollow:
    pattern: /walls/{id}/unfollow
    defaults:
        _controller: AdstacyAppBundle:Wall:unfollow
    requirements:
        id: \d+

adstacy_app_wall_create:
    pattern: /walls/create
    defaults:
        _controller: AdstacyAppBundle:Wall:add
