services:
    adstacy.admin.page:
        class: Adstacy\AppBundle\Admin\PageAdmin 
        tags:
            - { name: sonata.admin, manager_type: orm, group: app, label: "Page" }
        arguments:
            - ~
            - Adstacy\AppBundle\Entity\Page
            - 'SonataAdminBundle:CRUD'

    adstacy.admin.user:
        class: Adstacy\AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: app, label: "User" }
        arguments:
            - ~
            - Adstacy\AppBundle\Entity\User
            - 'SonataAdminBundle:CRUD'

    adstacy.admin.ad:
        class: Adstacy\AppBundle\Admin\AdAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: app, label: "Ads" }
        arguments:
            - ~
            - Adstacy\AppBundle\Entity\Ad
            - 'SonataAdminBundle:CRUD'

    adstacy.admin.featured_ad:
        class: Adstacy\AppBundle\Admin\FeaturedAdAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,group: app, label: "Featured Ads" }
        arguments:
            - ~
            - Adstacy\AppBundle\Entity\FeaturedAd
            - 'SonataAdminBundle:CRUD'
