services:
    adstacy.listener.set_locale:
        class: Adstacy\AppBundle\EventListener\SetLocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
