homepage:
    path:  /
    defaults:
        _controller: AdstacyAppBundle:App:index

adstacy_app_stream:
    path: /stream
    defaults:
        _controller: AdstacyAppBundle:App:stream

adstacy_app_trending:
    path: /trending
    defaults:
        _controller: AdstacyAppBundle:App:trending

adstacy_app_explore:
    path: /explore
    defaults:
        _controller: AdstacyAppBundle:App:explore

adstacy_app_upload:
    pattern: /upload
    defaults:
        _controller: AdstacyAppBundle:Ad:uploadImage
    options:
        expose: true

adstacy_app_upload_url:
    pattern: /upload-url
    defaults:
        _controller: AdstacyAppBundle:Ad:uploadImageFromUrl
    options:
        expose: true

adstacy_app_tags:
    path: /tags
    defaults:
        _controller: AdstacyAppBundle:App:tags

adstacy_app_favtags_add:
    path: /favtags/add
    defaults:
        _controller: AdstacyAppBundle:User:addFavouriteTags
    options:
        expose: true

adstacy_app_contact:
    path: /contact-us
    defaults:
        _controller: AdstacyAppBundle:App:contactUs

adstacy_app_who_to_follow:
    path: /who-to-follow
    defaults:
        _controller: AdstacyAppBundle:App:whoToFollow

adstacy_app_who_to_follow_facebook:
    path: /who-to-follow/facebook
    defaults:
        _controller: AdstacyAppBundle:App:whoToFollowFacebook

adstacy_app_who_to_follow_twitter:
    path: /who-to-follow/twitter
    defaults:
        _controller: AdstacyAppBundle:App:whoToFollowTwitter

adstacy_app_page_show:
    path: /pages/{key}
    defaults:
        _controller: AdstacyAppBundle:Page:show

AdstacyAppBundle_search:
    resource: "@AdstacyAppBundle/Resources/config/routing/search.yml"

AdstacyAppBundle_ads:
    resource: "@AdstacyAppBundle/Resources/config/routing/ads.yml"

AdstacyAppBundle_admin:
    resource: "@AdstacyAppBundle/Resources/config/routing/admin.yml"
    prefix: /admin
