homepage:
    pattern:  /
    defaults:
        _controller: AdstacyAppBundle:App:index

adstacy_app_contact:
    pattern: /contact
    defaults:
        _controller: AdstacyAppBundle:App:contact

adstacy_app_page_show:
    pattern: /pages/{key}
    defaults:
        _controller: AdstacyAppBundle:Page:show

AdstacyAppBundle_search:
    resource: "@AdstacyAppBundle/Resources/config/routing/search.yml"

AdstacyAppBundle_ads:
    resource: "@AdstacyAppBundle/Resources/config/routing/ads.yml"
