homepage:
    pattern:  /
    defaults:
        _controller: AdstacyAppBundle:App:index

AdstacyAppBundle_search:
    resource: "@AdstacyAppBundle/Resources/config/routing/search.yml"

AdstacyAppBundle_ads:
    resource: "@AdstacyAppBundle/Resources/config/routing/ads.yml"

AdstacyAppBundle_walls:
    resource: "@AdstacyAppBundle/Resources/config/routing/walls.yml"
