homepage:
    pattern:  /
    defaults:
        _controller: AdstacyAppBundle:App:index

adstacy_app_search:
    pattern: /search
    defaults:
        _controller: AdstacyAppBundle:App:search

adstacy_app_post_add:
    pattern: /posts/add
    defaults:
        _controller: AdstacyAppBundle:Post:add

adstacy_app_wall_add:
    pattern: /walls/add
    defaults:
        _controller: AdstacyAppBundle:Wall:add

adstacy_app_post_promote:
    pattern: /posts/{id}/promote
    defaults:
        _controller: AdstacyAppBundle:Post:promote

adstacy_app_post_unpromote:
    pattern: /posts/{id}/unpromote
    defaults:
        _controller: AdstacyAppBundle:Post:unpromote
