homepage:
    pattern:  /
    defaults:
        _controller: AdstacyAppBundle:App:index

adstacy_app_contact:
    pattern: /contact
    defaults:
        _controller: AdstacyAppBundle:App:contact

AdstacyAppBundle_search:
    resource: "@AdstacyAppBundle/Resources/config/routing/search.yml"

AdstacyAppBundle_ads:
    resource: "@AdstacyAppBundle/Resources/config/routing/ads.yml"
