homepage:
    pattern:  /
    defaults:
        _controller: AdstacyAppBundle:App:index

adstacy_app_stream:
    pattern: /stream
    defaults:
        _controller: AdstacyAppBundle:App:stream

adstacy_app_trending:
    pattern: /trending
    defaults:
        _controller: AdstacyAppBundle:App:trending

adstacy_app_explore:
    pattern: /explore
    defaults:
        _controller: AdstacyAppBundle:App:explore

adstacy_app_tags:
    pattern: /tags
    defaults:
        _controller: AdstacyAppBundle:App:tags

adstacy_app_usernames:
    pattern: /usernames/{q}
    defaults:
        _controller: AdstacyAppBundle:App:usernames

adstacy_app_contact:
    pattern: /contact-us
    defaults:
        _controller: AdstacyAppBundle:App:contactUs

adstacy_app_page_show:
    pattern: /pages/{key}
    defaults:
        _controller: AdstacyAppBundle:Page:show

AdstacyAppBundle_search:
    resource: "@AdstacyAppBundle/Resources/config/routing/search.yml"

AdstacyAppBundle_ads:
    resource: "@AdstacyAppBundle/Resources/config/routing/ads.yml"
