imports:
  - { resource: types.yml }
  - { resource: twig.yml }
  - { resource: admin.yml }
  - { resource: listener.yml }

services:
    adstacy.user.provider:
        class: Adstacy\AppBundle\Security\User\Provider\UserProvider
        arguments: [@fos_user.user_manager, @session, @router]
    
    adstacy.manager.user:
        class: Adstacy\AppBundle\Manager\UserManager
        arguments: [@service_container]

    adstacy.helper.formatter:
        class: Adstacy\AppBundle\Helper\Formatter

    adstacy.mobile_detect:
        class: Mobile_Detect

    adstacy.helper.user:
        class: Adstacy\AppBundle\Helper\UserHelper
        arguments: [@service_container]
    
    facebook:
        class: Facebook
        arguments:
            -
                appId: %facebook_app_id%
                secret: %facebook_app_secret%

    twitter:
        class: TwitterAPIExchange
        arguments:
            - 
                oauth_access_token: %twitter_access_token%
                oauth_access_token_secret: %twitter_access_token_secret%
                consumer_key: %twitter_client_id%
                consumer_secret: %twitter_client_secret%
