imports:
  - { resource: types.yml }
  - { resource: twig.yml }
  - { resource: admin.yml }

services:
    adstacy.user.provider:
        class: Adstacy\AppBundle\Security\User\Provider\UserProvider
        arguments: [@fos_user.user_manager, @session, @router]
