imports:
  - { resource: types.yml }
  - { resource: twig.yml }
  - { resource: admin.yml }
  - { resource: listener.yml }

services:
    adstacy.user.provider:
        class: Adstacy\AppBundle\Security\User\Provider\UserProvider
        arguments: [@fos_user.user_manager, @session, @router]
    
    adstacy.helper.formatter:
        class: Adstacy\AppBundle\Helper\Formatter

    adstacy.mobile_detect:
        class: Mobile_Detect

    adstacy.helper.user:
        class: Adstacy\AppBundle\Helper\UserHelper
        arguments: [@service_container]
    
    facebook:
        class: Facebook
        arguments:
            -
                appId: %facebook_app_id%
                secret: %facebook_app_secret%
