services:
    adstacy.twig.formatter_extension:
        class: Adstacy\AppBundle\Twig\FormatterExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    adstacy.twig.form_extension:
        class: Adstacy\AppBundle\Twig\FormExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    adstacy.twig.user_extension:
        class: Adstacy\AppBundle\Twig\UserExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    adstacy.twig.extension:
        class: Adstacy\AppBundle\Twig\AdstacyExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
