services:
    adstacy.type.image:
        class: Adstacy\AppBundle\Form\Type\ImageType
        tags:
            - { name: form.type, alias: image }

    adstacy.type.hashtags:
        class: Adstacy\AppBundle\Form\Type\HashtagsType
        tags:
            - { name: form.type, alias: hashtags }

    adstacy.type.purified_textarea:
        class: Adstacy\AppBundle\Form\Type\PurifiedTextareaType
        arguments: [@adstacy.form.transformer.html_purifier]
        tags:
            - { name: form.type, alias: purified_textarea }

    adstacy.type.wysihtml5:
        class: Adstacy\AppBundle\Form\Type\Wysihtml5Type
        arguments: [@adstacy.form.transformer.html_purifier]
        tags:
            - { name: form.type, alias: wysihtml5 }

    adstacy.type.ad_images:
        class: Adstacy\AppBundle\Form\Type\AdImageCollectionType
        arguments: [@adstacy.form.transformer.images_to_ids_transformer]
        tags:
            - { name: form.type, alias: ad_images }

    adstacy.form.transformer.html_purifier:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments: [@exercise_html_purifier.default]

    adstacy.form.transformer.images_to_ids_transformer:
        class: Adstacy\AppBundle\Form\DataTransformer\ImagesToIdsTransformer
        arguments: [@doctrine.orm.entity_manager, @security.context]
