services:
    adstacy.type.image:
        class: Adstacy\AppBundle\Form\Type\ImageType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: image}

